{
 "title": "Terraform Enterprise",
 "description": "A Grafana dashboard for Terraform Enterprise ",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(tfe_run_count, instance)"
    }
   },
   { "name": "rangeinterval", "query": "10s,30s,1m,2m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Container Stats (TFE Services)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance, name)((rate(tfe_container_cpu_usage_kernel_ns{instance=\"$node\",run_type=\"\"}[$rangeinterval]) + rate(tfe_container_cpu_usage_user_ns{instance=\"$node\",run_type=\"\"}[$rangeinterval])) / 1e7)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance, name)(tfe_container_memory_used_bytes{instance=\"$node\",run_type=\"\"}) / 1024 / 1024",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Disk I/O Read",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance, name)(rate(tfe_container_disk_io_op_read_total{instance=\"$node\",run_type=\"\"}[$rangeinterval]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Disk I/O Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance, name)(rate(tfe_container_disk_io_op_write_total{instance=\"$node\",run_type=\"\"}[$rangeinterval]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Traffic Ingress (BW)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (instance, name)(rate(tfe_container_network_rx_bytes_total{instance=\"$node\",run_type=\"\"}[$rangeinterval])) / 1024",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Traffic Egress (BW)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (instance, name)(rate(tfe_container_network_tx_bytes_total{instance=\"$node\",run_type=\"\"}[$rangeinterval])) / 1024",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Traffic Ingress (Packets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (instance, name)(rate(tfe_container_network_rx_packets_total{instance=\"$node\",run_type=\"\"}[$rangeinterval]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Traffic Egress (Packets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by (instance, name)(rate(tfe_container_network_tx_packets_total{instance=\"$node\",run_type=\"\"}[$rangeinterval]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance)(count(tfe_container_cpu_usage_kernel_ns{instance=\"$node\"}))"
    }
   ]
  },
  {
   "title": "Container Process Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(tfe_container_process_count{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Current Container Run Counts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(tfe_run_count)" },
    { "expr": "sum(tfe_run_limit)" }
   ]
  },
  { "title": "Run Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Current Terraform Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by(status)(tfe_run_current_count{status=~\"planning|applying\"})",
     "legendFormat": "{{ run_type }}"
    }
   ]
  },
  {
   "title": "Total Runs Processed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tfe_run_current_count{status=~\"applied|errored|planned_and_finished\"})"
    }
   ]
  },
  {
   "title": "Run Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tfe_run_current_count{status=\"errored\"})"
    }
   ]
  },
  {
   "title": "Top Run Counts (per Workspace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "topk(5, count by(workspace_name, organization_name)(tfe_run_current_count))",
     "legendFormat": "{{ workspace_name }} - {{organization_name}}"
    }
   ]
  },
  {
   "title": "Current Run Breakdown (per Organization)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 52 },
   "targets": [
    {
     "expr": "sum by(organization_name)(tfe_run_current_count{status!~\"applied|errored|discarded|canceled|planned_and_finished\"})",
     "legendFormat": "{{organization_name}}"
    }
   ]
  },
  {
   "title": "Runs In Queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tfe_run_current_count{status=~\"(?:(?:plan|apply)?_)?queued|pending\"})"
    }
   ]
  },
  {
   "title": "Runs Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status)(tfe_run_current_count{status!~\"applied|errored|discarded|canceled|planned_and_finished\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Run Completion Rate (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "targets": [
    {
     "expr": "rate(sum by(status)(tfe_run_current_count{status=~\"applied|planned_and_finished|errored|discarded|canceled\"})[30s:]) * 60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Meta Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Metrics Collection Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, quantile)(tfe_metrics_collect_duration_ms{instance=\"$node\"})",
     "legendFormat": "Quantile - {{ quantile }}"
    }
   ]
  },
  {
   "title": "StatsD Received Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tfe_metrics_statsd_bytes_count[$rangeinterval:]))",
     "legendFormat": "Received Byte Rate"
    }
   ]
  },
  {
   "title": "StatsD Received Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tfe_metrics_statsd_packet_count[$rangeinterval:]))",
     "legendFormat": "Received Packet Rate"
    }
   ]
  }
 ]
}